### ISSUE TITLE
compilation can not pass

### ISSUE THREAD

**Issue by wphu** [bendudson/hermes-3#1]
Hello,

I compile hermes-3 under BOUT-dev master brach (now the latest version is 4.3.1 ), it can not pass, the error is shown below. It seems that "include/hermes_utils.hxx" is missing.
```
  Compiling  collisions.cxx
collisions.cxx:6:10: fatal error: ../include/hermes_utils.hxx: No such file or directory
 #include "../include/hermes_utils.hxx"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [../../../make.config:326: collisions.o] Error 1
make: *** [../../make.config:141: src] Error 2

```

Thanks.

**Comment by bendudson** [comment]
Sorry, I forgot to add that file. I've added it now, and will try to set up Travis to run the tests automatically. Thanks!

**Comment by wphu** [comment]
OK，I will retry.

**Comment by bendudson** [comment]
It compiles fine on my laptop,  but I'm getting errors on Travis.  I'll try to fix those and let you know when it's working

**Comment by wphu** [comment]
OK, thanks.

**Comment by bendudson** [comment]
I've changed the code to work with the `next` branch of BOUT++. The tests now pass on Travis, so hopefully it will be easier to get working on your system. Some examples are working, see the `examples/` subdirectory, but it's still limited and definitely a work in progress.

**Comment by wphu** [comment]
OK, I will try on Monday, thank you.
