### ISSUE TITLE
Linear examples cross section not plotting correctly

### ISSUE THREAD

**Issue by jgabriel6157** [bendudson/hermes-3#113]
Running plot_crossection.py after running any of the linear examples results in a blank plot:

![Ne_crossection_1](https://user-images.githubusercontent.com/85511789/221223193-7a7f1e9c-645f-435f-9c37-940aa9998b0c.png)

It appears that `g_33` is not being correctly output to the data file as `g_33 = collect("g_33", path=path, yind=yind).squeeze()` in plot_crossection.py yields an array of 1's. Hard coding in the correct array for `g_33` in plot_crossection.py yields the correct plot: 

![Ne_crossection_1Works](https://user-images.githubusercontent.com/85511789/221224691-ff45c1b3-7a19-4c18-a460-3927d2fb18db.png)

I believe the issue was introduced somewhere in #72 as this issue is not present in #86 (the previous merge pull request) and prior.

**Comment by bendudson** [comment]
Thanks @jgabriel6157 ! There was a major update to BOUT++ in #72, including changing how output are written. It looks like the way metric tensor components are written has changed. I'll investigate.

**Comment by bendudson** [comment]
I think this is now fixed
