### ISSUE TITLE
`cmake -E copy_directory` fails while editing

### ISSUE THREAD

**Issue by dschwoerer** [bendudson/hermes-3#149]
emacs uses symlinks to lock files that are currently edited.

`cmake -E copy_directory` chocks on those links, and the copy_directory fails without any explanation.

This should be avoidable by explicitly copying the files, rather than whole directories.

See also:
https://cmake.org/pipermail/cmake/2009-September/032219.html

**Comment by bendudson** [comment]
Hi @dschwoerer Sorry I think the solution is either in CMake or emacs
