### ISSUE TITLE
Issue with neutral boundaries for MAST-U SXD grid 

### ISSUE THREAD

**Issue by PoloidalLloyd** [bendudson/hermes-3#215]
Trying to run a MAST-U 2D case with puff and pump however after adding sources to the grid, we ran into issues with cvode crashing on the first step with the error:

"""
[CVODE ERROR]  CVode
At t = 0 and h = 1.69407e-19, the corrector convergence test failed repeatedly or with |h| = hmin.
"""
I have attached the inp and files for this failed run (2024-03-19_MAST-U_2D_failed_run).
[failed_run.txt](https://github.com/bendudson/hermes-3/files/14704855/failed_run.txt)

We then stripped back the simulation and removed many options, most notably removing the puff, pump and source terms from the grid, changing the boundary conditions in the core to be Dirichlet instead of Neumann and setting a constant temperature, and finally (the thing that resulted in having a simulation run) was setting all neutral_boundary conditions to False and setting kappa_limit_alpha = 1 for all species. This resulted in a simulation being able to run.

I have attached the grid and input file for this successful run 
[successful_run.txt](https://github.com/bendudson/hermes-3/files/14704851/successful_run.txt)

and the respective grids can be found in these zips.

[2024-03-19_MAST-U_2D_failed_run.zip](https://github.com/bendudson/hermes-3/files/14704860/2024-03-19_MAST-U_2D_failed_run.zip)
[2024-03-19_MAST-U_2D_stripped_back_successful_run.zip](https://github.com/bendudson/hermes-3/files/14704864/2024-03-19_MAST-U_2D_stripped_back_successful_run.zip)

Thanks in advance!

**Comment by mikekryjak** [comment]
This was caused by running an older version of Hermes-3 before this PR fixed the bug:
https://github.com/bendudson/hermes-3/pull/191
