### ISSUE TITLE
Inconsistency in kinetic boundary correction

### ISSUE THREAD

**Issue by dschwoerer** [bendudson/hermes-3#217]
Here the gradient goes from the last point in the boundary to the first one in the boundary:
https://github.com/bendudson/hermes-3/blob/master/src/sheath_boundary.cxx#L198
with a cutoff of 1e-3:
https://github.com/bendudson/hermes-3/blob/master/src/sheath_boundary.cxx#L203

While here it goes only to the sheath:
https://github.com/bendudson/hermes-3/blob/master/src/sheath_boundary.cxx#L530
but with the same cutoff:
https://github.com/bendudson/hermes-3/blob/master/src/sheath_boundary.cxx#L533

Thus the cutoffs differs by a factor of 2.

**Comment by bendudson** [comment]
Fixed in 2faaa3c5 : The calculations are still different, but the cutoff is now a factor of 2 different to compensate.
