### ISSUE TITLE
The problem of sheath boundary

### ISSUE THREAD

**Issue by lqs661** [bendudson/hermes-3#219]
When I runned the pure H/D/T cases, the velocity at target output by program seeemed not equal  to sound speed.  According to this article D. Tskhakaya, S. Kuhn / Journal of Nuclear Materials 337–339 (2005) 405–409, for single-ion case, the sound speed is equal to: 
![image](https://github.com/bendudson/hermes-3/assets/111937551/90f254a4-796d-4094-832a-31d62a8a03eb)
For default settings, the sin(α)=1, and the adiabatic constant X_i=5/3. I used the target temperature output by program to calculated the sound speed and compared to the velocity output by program. The detailed results as follows:
![image](https://github.com/bendudson/hermes-3/assets/111937551/8a336731-ddda-45a2-bc03-c1dad7df2ece)
The velocity output by program is lower than sound speed. I have imported the [sheath_boundary] module and set upper_y=true. What could caused this issue?

**Comment by bendudson** [comment]
Which value are you taking as `v_target`? The target is half-way between cells, so to get the velocity at the boundary you have to collect the data including Y (parallel) guard cells:
```
v = collect("Vd+", yguards=True)
```
There are two guard cells, so we have:
```
ny - 3 || ny - 2 | ny - 1
       ^ boundary
```
so the velocity at the target is the average of v in the cell with y index "-3" and index "-2":
```
v_target = 0.5 * (v[:, 0, -3, 0] + v[:, 0, -2, 0])
```
Note: When calculating the sheath velocity, the electron and ion temperatures should also be calculated at the target, half-way between cells "-3" and "-2".
The calculation of the sheath velocity is here:
https://github.com/bendudson/hermes-3/blob/master/src/sheath_boundary.cxx#L614

It is sometimes also useful to try the simpler sheath implementation, if there is only one ion species: Replace `sheath_boundary` with `sheath_boundary_simple` in the BOUT.inp input. The simple sheath boundary allows you to specify the `gamma_e` and `gamma_i` sheath heat transmission coefficients. The implementation of the flow speed in this component is:
https://github.com/bendudson/hermes-3/blob/master/src/sheath_boundary_simple.cxx#L567

**Comment by lqs661** [comment]
Thank you for your suggestion! Now it worked. Previously, I use 'v = collect("Vd+",tind=-1)[-1,0,1:-1,0], v_tar = v[-1]' to get target velocity. Maybe it's wrong. Besides, for upstream quantities, should I use 'v = collect("Vd+",tind=-1,yguards=True)[-1,0,1:-1,0], v_up = 0.5 * (v[1] + v[2]) to get upstream velocity?
