### ISSUE TITLE
The profile of neutral velocity

### ISSUE THREAD

**Issue by lqs661** [bendudson/hermes-3#226]
When I runned the 1D pure hydrogen isotope cases, there is a strange change in 1D neutral velocity curve.
![image](https://github.com/bendudson/hermes-3/assets/111937551/0356060f-bf55-4e65-b594-6ba8cee5a948)
I'm not sure whether this is a bug or numerical error.

**Comment by mikekryjak** [comment]
Hi @lqs661, have you made sure that the simulation is in steady state? Is it attached or detached?
Also, sorry for missing these issues. We have a Slack channel which would be an easier way to help you with these issues. Can you send me your email address so I can add you?

**Comment by lqs661** [comment]
I think it is in steady state and it's detached. This is my email lqs1999@mail.ustc.edu.cn
