### ISSUE TITLE
Particles not conserved?

### ISSUE THREAD

**Issue by GF-Abetharan-Antony** [bendudson/hermes-3#247]
Hello,

I am running a non-conventional setup where along y variation is not of importance and only the radial is. 

-  I run with fixed velocity of 0 and evolution of all other equations. 
-  bndry_xout = free_o3 for all density terms 
-  bndry_xout = dirichlet on the deuterium/electron pressures
-  Recycling happening at bndry_xout for impurity and main species. 

Appears to be generating impurities, uncertain how. I have attached the BOUT.inp as a txt file. A simple sum of ionised impurities see orders of magnitude increase in density from t=0 to t=-1 (no initialized background neutral impurity) 

Tested not using neutral_mixed and appears to preserve particles as expected. 

I am guessing I am doing something strange, though not completely certain. 

[BOUT.txt](https://github.com/user-attachments/files/16628261/BOUT.txt)

**Comment by bendudson** [comment]
Hi @GF-Abetharan-Antony !
This is a slightly unusual setup, but we should be able to get this working. What is the model intended to be in the parallel direction? Is there no flow of energy or particles in Y? Should ions recycle from the outer walls (in X)?
Thanks!
Ben

**Comment by GF-Abetharan-Antony** [comment]
Indeed! Thanks for the help! 

The big picture we trying to simulate is a core flux-tube in contact with a wall with all particle and power loss is due to the outer radial wall.  

Answers to your questions:

- The Y-axis should have no loss of energy/particles. 
- Ions should recycle from the outer wall

**Comment by GF-Abetharan-Antony** [comment]
Hi Ben,
Happy to take a look at this myself, if you have any suggestions where to look, I will do a dive.

Abi

**Comment by mikekryjak** [comment]
Hi @GF-Abetharan-Antony, what's your email address? I can add you to our Slack channel, where it's a bit easier to discuss and troubleshoot these things.

**Comment by GF-Abetharan-Antony** [comment]
abetharan.antony@generalfusion.com

**Comment by GF-Abetharan-Antony** [comment]
After Discussions with @mikekryjak, no bug, using free_o3 boundary condition choices lend itself to influx of impurities, some solutions discussed but preliminarily will simply work with a decay length BC instead.

**Comment by bendudson** [comment]
Thanks @mikekryjak and @GF-Abetharan-Antony !
