### ISSUE TITLE
Inconsistent velocity definition

### ISSUE THREAD

**Issue by mikekryjak** [bendudson/hermes-3#68]
In evolve_momentum.cxx, we define velocity as flux divided by density * atomic number. This is also where velocity and density are saved out.
https://github.com/bendudson/hermes-3/blob/fc1a8a0f91b5b91e521691904f33f9afb9226dbc/src/evolve_momentum.cxx#L230

But in sheath_boundary_simple.cxx, we no longer have the atomic number factor when calculating the guard cell flux `NVi[ip]`. N.B. this expression comes from `NVi(sheath) = [NVi(guard) + NVi(last)]/2` rearranged into `NVi(guard) = [2*NVi(sheath) -NVi(last)]`. 
https://github.com/bendudson/hermes-3/blob/fc1a8a0f91b5b91e521691904f33f9afb9226dbc/src/sheath_boundary_simple.cxx#L302

This is also visible in results. Performing `NVd+ / Nd+ / Vd+` on raw results (with no de-normalisation and no processing) results in a factor `2` everywhere apart from in the guard cell. 

I am getting myself a bit confused as to which one is right. I thought that `NVi = Ne * Vi` by definition and represents the flux of particles, thereby having no link to atomic number or mass. Another confusion is that NVi is often labelled as momentum while (I think?) it's flux in `[m^-2s-1]`. 

@bendudson thoughts?

**Comment by bendudson** [comment]
Hey @mikekryjak It looks like the electron momentum includes this factor:
https://github.com/bendudson/hermes-3/blob/master/src/sheath_boundary_simple.cxx#L302
but indeed the ion momentum does not:
https://github.com/bendudson/hermes-3/blob/master/src/sheath_boundary_simple.cxx#L470

The full "sheath_boundary" component does include this factor:
https://github.com/bendudson/hermes-3/blob/master/src/sheath_boundary.cxx#L519

**Comment by mikekryjak** [comment]
@bendudson I just tried putting the factor back in, and it doesn't fix it. I changed the line to:
`NVi[ip] = 2. * Mi * nisheath * visheath - NVi[i];`

Calculating `NVd+ / Nd+ / Vd+` on the result yields a factor of 4.81 instead of a factor of 2.0 (which would be correct) or ~2.3 (like before). Potentially offsetting errors or I'm doing something wrong.

**Comment by bendudson** [comment]
@mikekryjak have to be a bit careful with these nonlinear terms. If you calculate the flux at the sheath from `flux = 0.5 * (NVi[ip] + NVi[i]) / A` where `A` is the atomic mass, and then the density at the sheath from `density = 0.5 * (N[ip] + N[i])` and `velocity = 0.5 * (V[ip] + V[i])` then you should get that `flux = density * velocity`.

**Comment by bendudson** [comment]
It looks like the momentum (`NV`) variable is not used in the density, momentum or pressure evolution equations. It is however used in the vorticity equation to calculate the total parallel current density:
https://github.com/bendudson/hermes-3/blob/master/src/vorticity.cxx#L569

**Comment by mikekryjak** [comment]
@bendudson I think I have a problem in that I am confused about the definition of NVi. In the SD1D manual and in my head, NVi is particle flux per area in units [m-2s-1].
But in Hermes-3, it's multiplied by the atomic mass... 
What is the exact, precise definition of NVi including units in Hermes-3?

**Comment by bendudson** [comment]
Hey @mikekryjak It's the momentum density, rather than the particle flux. Dividing by AA gives the particle flux as it was in SD1D. 

For example, the `NVd+` output if multiplied by `m_p * Nnorm * Cs0` is the momentum density, or equivalently mass flux, with units of [kg m^-2 s^-1].  `m_p` here is the proton mass.

Taking out the AA factor gives particle flux, so `NVd+ / 2` multiplied by `Nnorm * Cs0` is the particle flux with units of [m^-2 s^-1]

**Comment by mikekryjak** [comment]
OK, thanks. It may be worth including a table of variables, normalisations and units in the manual in the style of what's in SD1D. I don't think there is one at the  moment.
