### ISSUE TITLE
Franck-Condon Energy Missing

### ISSUE THREAD

**Issue by mikekryjak** [bendudson/hermes-3#70]
In SD1D recycled neutrals start with 3.5eV, the Franck-Condon energy. 
I cannot find any neutral energy source term linked to recycled neutrals, which means that they start with zero energy... unless I've missed something obvious!

**Comment by mikekryjak** [comment]
@bendudson am I correct in thinking this is missing?
Hasan and I found the relevant bit in Hermes-2:

https://github.com/bendudson/hermes-2/blob/45b2b7824bbe2c8ff1d8641534289d0675b10181/src/hermes-2.cxx#L3823-L3826

The neutrals get both the F-C energy as well as momentum which is defined by this:
https://github.com/bendudson/hermes-2/blob/45b2b7824bbe2c8ff1d8641534289d0675b10181/src/hermes-2.cxx#L385

This is also how it seems to work in SD1D:
https://github.com/boutproject/SD1D/blob/60160d8d9df3eee8f265d02d6b69f2d70e3a5276/sd1d.cxx#L1543-L1553

**Comment by bendudson** [comment]
Hey @mikekryjak Yes you're correct that this energy source is missing, so neutrals are recycled with zero temperature. The code to perform the recycling is here:
https://github.com/bendudson/hermes-3/blob/master/src/recycling.cxx#L85
It adds a source of density, and would need to add a source of energy and momentum.

**Comment by mikekryjak** [comment]
@bendudson when implementing this back I think it's worth emulating what Hermes-2 does with wall_power. It's a useful output and has a surface recombination heat source which I hadn't considered before:
https://github.com/bendudson/hermes-2/blob/45b2b7824bbe2c8ff1d8641534289d0675b10181/src/hermes-2.cxx#L3829

I can have a go at implementing all of this tomorrow

**Comment by mikekryjak** [comment]
Implemented as recycle_energy
